/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentIndexRouteImport } from './routes/assessment.index'
import { Route as OnboardingIntroRouteImport } from './routes/onboarding.intro'
import { Route as OnboardingChallengesRouteImport } from './routes/onboarding.challenges'
import { Route as OnboardingBasicInfoRouteImport } from './routes/onboarding.basic-info'
import { Route as OnboardingAssessmentIntroRouteImport } from './routes/onboarding.assessment-intro'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AssessmentRecommendationsRouteImport } from './routes/assessment.recommendations'
import { Route as AssessmentProcessingRouteImport } from './routes/assessment.processing'
import { Route as AssessmentDiscoveryRouteImport } from './routes/assessment.discovery'
import { Route as AppHomeRouteImport } from './routes/_app.home'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIndexRoute = AssessmentIndexRouteImport.update({
  id: '/assessment/',
  path: '/assessment/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIntroRoute = OnboardingIntroRouteImport.update({
  id: '/onboarding/intro',
  path: '/onboarding/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingChallengesRoute = OnboardingChallengesRouteImport.update({
  id: '/onboarding/challenges',
  path: '/onboarding/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBasicInfoRoute = OnboardingBasicInfoRouteImport.update({
  id: '/onboarding/basic-info',
  path: '/onboarding/basic-info',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAssessmentIntroRoute =
  OnboardingAssessmentIntroRouteImport.update({
    id: '/onboarding/assessment-intro',
    path: '/onboarding/assessment-intro',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRecommendationsRoute =
  AssessmentRecommendationsRouteImport.update({
    id: '/assessment/recommendations',
    path: '/assessment/recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentProcessingRoute = AssessmentProcessingRouteImport.update({
  id: '/assessment/processing',
  path: '/assessment/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentDiscoveryRoute = AssessmentDiscoveryRouteImport.update({
  id: '/assessment/discovery',
  path: '/assessment/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/home': typeof AppHomeRoute
  '/assessment/discovery': typeof AssessmentDiscoveryRoute
  '/assessment/processing': typeof AssessmentProcessingRoute
  '/assessment/recommendations': typeof AssessmentRecommendationsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/assessment-intro': typeof OnboardingAssessmentIntroRoute
  '/onboarding/basic-info': typeof OnboardingBasicInfoRoute
  '/onboarding/challenges': typeof OnboardingChallengesRoute
  '/onboarding/intro': typeof OnboardingIntroRoute
  '/assessment/': typeof AssessmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/home': typeof AppHomeRoute
  '/assessment/discovery': typeof AssessmentDiscoveryRoute
  '/assessment/processing': typeof AssessmentProcessingRoute
  '/assessment/recommendations': typeof AssessmentRecommendationsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/assessment-intro': typeof OnboardingAssessmentIntroRoute
  '/onboarding/basic-info': typeof OnboardingBasicInfoRoute
  '/onboarding/challenges': typeof OnboardingChallengesRoute
  '/onboarding/intro': typeof OnboardingIntroRoute
  '/assessment': typeof AssessmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/_app/home': typeof AppHomeRoute
  '/assessment/discovery': typeof AssessmentDiscoveryRoute
  '/assessment/processing': typeof AssessmentProcessingRoute
  '/assessment/recommendations': typeof AssessmentRecommendationsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/assessment-intro': typeof OnboardingAssessmentIntroRoute
  '/onboarding/basic-info': typeof OnboardingBasicInfoRoute
  '/onboarding/challenges': typeof OnboardingChallengesRoute
  '/onboarding/intro': typeof OnboardingIntroRoute
  '/assessment/': typeof AssessmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/home'
    | '/assessment/discovery'
    | '/assessment/processing'
    | '/assessment/recommendations'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/onboarding/assessment-intro'
    | '/onboarding/basic-info'
    | '/onboarding/challenges'
    | '/onboarding/intro'
    | '/assessment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/home'
    | '/assessment/discovery'
    | '/assessment/processing'
    | '/assessment/recommendations'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/onboarding/assessment-intro'
    | '/onboarding/basic-info'
    | '/onboarding/challenges'
    | '/onboarding/intro'
    | '/assessment'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/welcome'
    | '/_app/home'
    | '/assessment/discovery'
    | '/assessment/processing'
    | '/assessment/recommendations'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/onboarding/assessment-intro'
    | '/onboarding/basic-info'
    | '/onboarding/challenges'
    | '/onboarding/intro'
    | '/assessment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  AssessmentDiscoveryRoute: typeof AssessmentDiscoveryRoute
  AssessmentProcessingRoute: typeof AssessmentProcessingRoute
  AssessmentRecommendationsRoute: typeof AssessmentRecommendationsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  OnboardingAssessmentIntroRoute: typeof OnboardingAssessmentIntroRoute
  OnboardingBasicInfoRoute: typeof OnboardingBasicInfoRoute
  OnboardingChallengesRoute: typeof OnboardingChallengesRoute
  OnboardingIntroRoute: typeof OnboardingIntroRoute
  AssessmentIndexRoute: typeof AssessmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/': {
      id: '/assessment/'
      path: '/assessment'
      fullPath: '/assessment/'
      preLoaderRoute: typeof AssessmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/intro': {
      id: '/onboarding/intro'
      path: '/onboarding/intro'
      fullPath: '/onboarding/intro'
      preLoaderRoute: typeof OnboardingIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/challenges': {
      id: '/onboarding/challenges'
      path: '/onboarding/challenges'
      fullPath: '/onboarding/challenges'
      preLoaderRoute: typeof OnboardingChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/basic-info': {
      id: '/onboarding/basic-info'
      path: '/onboarding/basic-info'
      fullPath: '/onboarding/basic-info'
      preLoaderRoute: typeof OnboardingBasicInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/assessment-intro': {
      id: '/onboarding/assessment-intro'
      path: '/onboarding/assessment-intro'
      fullPath: '/onboarding/assessment-intro'
      preLoaderRoute: typeof OnboardingAssessmentIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/recommendations': {
      id: '/assessment/recommendations'
      path: '/assessment/recommendations'
      fullPath: '/assessment/recommendations'
      preLoaderRoute: typeof AssessmentRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/processing': {
      id: '/assessment/processing'
      path: '/assessment/processing'
      fullPath: '/assessment/processing'
      preLoaderRoute: typeof AssessmentProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/discovery': {
      id: '/assessment/discovery'
      path: '/assessment/discovery'
      fullPath: '/assessment/discovery'
      preLoaderRoute: typeof AssessmentDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  AssessmentDiscoveryRoute: AssessmentDiscoveryRoute,
  AssessmentProcessingRoute: AssessmentProcessingRoute,
  AssessmentRecommendationsRoute: AssessmentRecommendationsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  OnboardingAssessmentIntroRoute: OnboardingAssessmentIntroRoute,
  OnboardingBasicInfoRoute: OnboardingBasicInfoRoute,
  OnboardingChallengesRoute: OnboardingChallengesRoute,
  OnboardingIntroRoute: OnboardingIntroRoute,
  AssessmentIndexRoute: AssessmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
